### PR TITLE
Run widoco with unprivileged user in container

### PR DESCRIPTION
**Pull request by janvlug**
- The container runs WIDOCO now as an unprivileged user
- Example works now also with SELinux

### CODE REVIEW

**Comment by dgarijo** [comment]
For some reason this does not pass all the tests. I do not understand, since it does not modify the code at all...

**Comment by vChavezB** [comment]
The error occured with the `testOntologyFromURL`. Perhaps an anomaly happened while retrieving the ontology from the url.

**Comment by janvlug** [comment]
I'm also surprised by the failing tests. Maybe indeed an anomaly when retrieving the URL. Locally the tests run successfully for me. Is there a way to trigger the tests on GitHub again? Or should I close this Pull request and try to create a new one, and see if the test will succeed then?

**Comment by vChavezB** [comment]
You could force trigger the pipeline by adding an ammended commit.

git commit --amend 

do not change the commit message and then

git push origin --force

Not the nicest way but this way you can retrigger the github actions by making github detect the "new" commit.

**Comment by dgarijo** [comment]
No need to close the PR. I think it's just fine because the code was not changed.  Merging

**Comment by dgarijo** [comment]
Just next time please do PRs  into develop. Thanks!

**Pull request merged**
