### PR TITLE
Upgraded webvowl to 1.1.4 and removed dependency on xercesImpl

### PR DESCRIPTION
**Pull request by jgeluk**

### CODE REVIEW

**Comment by jgeluk** [comment]
Done now with this one, it works

**Comment by jgeluk** [comment]
Doesn't work, it always takes the foaf ontology, not the generated webvowl/data/ontology.json file. @dgarijo I suppose you tweaked the webvowl.zip file to make that work?

**Comment by dgarijo** [comment]
Yes, I did. And I also modified slightly the html page so some options that are not relevant would be hidden.

**Comment by jgeluk** [comment]
I compared the original webvowl.zip and webvowl_orginal.zip and only found one difference, the string "foaf" being replaced by "ontology". Didn't see those changes in the html file that you mentioned.

**Comment by dgarijo** [comment]
There are a few changes in the html. One specifying that I had integrated the tool and another removing the examples. It was pretty basic. I will have a look whenever I have more time. Thanks!

**Comment by dgarijo** [comment]
Thanks for this. I have modified this a little so your name appears in the credits for the integration too. WIll push soon

**Pull request merged**
