### PR TITLE
#294 Added optional parameter to display only direct imports

### PR DESCRIPTION
**Pull request by kartgk**
@dgarijo Tried to address this in my own fork and seems to work. Please take a look and merge if you think it is appropriate. Else please ignore.

### CODE REVIEW

**Comment by dgarijo** [comment]
Thanks! I am traveling but I will have a look at this as soon as I can.
Best,
Daniel

**Comment by kartgk** [comment]
@dgarijo Did you get a chance to look at this merge request.

**Comment by dgarijo** [comment]
@kartgk,
I have been travelling for the last 2-3 weeks and will unfortunately be out
until the end of the month. So not yet.

**Comment by dgarijo** [comment]
Thanks again for your contributions. Please next time push to the develop branch ;)

**Pull request merged**
