### PR TITLE
refactoring most of system println to logger, with SLF4J

### PR DESCRIPTION
**Pull request by seralf**
Hi this is a simple (first) attempt to suggest how to improve logging, as suggested with the issue #342 .

I maintened all the system logging where they are actually on the terminal, and introduce instead SLF4J where needed instead.

### CODE REVIEW

**Comment by dgarijo** [comment]
Hi @seralf,
thanks for your contribution.  Please as indicated in the contribution guidelines (https://github.com/dgarijo/Widoco#contribution-guidelines) push your PR to the *develop branch*. The master branch has the code of the latest published release. I will close this PR in the meantime.

**Comment by dgarijo** [comment]
But please don't forget to push it!!

**Comment by seralf** [comment]
sorry i pushed on the wrong branch by mistake, I'll correct it tomorrow

Il giorno mer 8 mag 2019 alle ore 01:07 Daniel Garijo <
notifications@github.com> ha scritto:

**Comment by dgarijo** [comment]
Thanks!

**Pull request closed without merging**
