### PR TITLE
Update and rename it.properties (to do) to it.properties

### PR DESCRIPTION
**Pull request by seralf**
italian translation (first version)

### CODE REVIEW

**Comment by dgarijo** [comment]
Thanks!! I see that this PR does not include many properties though (see the https://github.com/dgarijo/Widoco/blob/master/src/main/resources/widoco/en.properties). It would be awesome if you can complete those too. Otherwise, we will probably end up with a mixup in the documentation

**Comment by seralf** [comment]
ok, I'll check them... I used the file referenced earlier, but there are
many more! I'll update it soon, if this works :-)

Il giorno mer 1 lug 2020 alle ore 22:26 Daniel Garijo <
notifications@github.com> ha scritto:

**Comment by dgarijo** [comment]
Yeah, when I added more metadata fields, I expanded the language templates. However, the old one that remained to do was incomplete.

**Comment by seralf** [comment]
Hello, I improved a bit the translation, adding other properties as suggested, in #422.
Some term should not be translated, and there could be still issues when rendering to HTML, due to different length of text, but I think it should work for a first version.

**Pull request merged**
