### PR TITLE
improved maven descriptor

### PR DESCRIPTION
**Pull request by seralf**
improved maven descriptor:
* added attachments for sources and javadoc
* fixed encoding to standard UTF-8
* added note with instructions for maven deploy

### CODE REVIEW

**Comment by dgarijo** [comment]
@seralf,
please add changes in the future to the develop branch. The main branch is for releases only

**Comment by dgarijo** [comment]
@seralf, sorry but your changes make the project not to compile due to encoding issues. Since I don't want to fix by hand all the problems, I will use the old POM file. I will keep the maven instructions!

**Comment by seralf** [comment]
no problem, please fix the encoding to standard UTF-8!

**Comment by dgarijo** [comment]
Done

**Pull request merged**
