### PR TITLE
italian language translation first draft

### PR DESCRIPTION
**Pull request by seralf**
first attempt to a basic translation in italian language

### CODE REVIEW

**Comment by dgarijo** [comment]
@seralf,
can you please push to the development branch? That's where I work on the next updates before merging in master. Thanks in advance!
Also, can you please rename the file to it.properties? (without the `to do`). Otherwise it won't load.

**Comment by dgarijo** [comment]
And thanks for the PR :)

**Comment by seralf** [comment]
oh sorry :-)

**Comment by dgarijo** [comment]
Closing this PR

**Pull request closed without merging**
